<?php
$this->headLink(array('rel' => 'shortcut icon', 'href' => $this->baseUrl('resources/images/favicon.ico')), 'PREPEND')
        ->prependStylesheet($this->baseUrl('resources/css/style.css'), 'screen');

$this->headScript()
        ->appendFile($this->baseUrl('resources/js/jquery-1.5.1.min.js'))
        ->appendFile($this->baseUrl('resources/js/script.js'));

?>
<?php echo $this->docType() ?>
<html>
    <head>
        <?php echo $this->headTitle(); ?>
        <base href="<?php echo $this->baseUrl(); ?>" />

        <?php echo $this->headLink(); ?>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>

        <div id="wrapper">
            <div id="container">
                <?php echo $this->partial('index/menu.phtml', 'default'); ?>
                <div class='mp'>
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>
