                <ul id="menu">
                    <li><a href="<?php echo $this->baseUrl('#introduction'); ?>">Introduction</a></li>
                    <li><a href="<?php echo $this->baseUrl('#api'); ?>">Api</a></li>
                    <li><a href="<?php echo $this->baseUrl('#security'); ?>">Security</a></li>
                    <li><a href="<?php echo $this->baseUrl('#configuration'); ?>">Configuration</a></li>
                    <li><a href="<?php echo $this->baseUrl('generate'); ?>">Generate PDF</a></li>
                </ul>
